### PR TITLE
Pull Request for New York Times Page

### PR DESCRIPTION
**Pull request by teekaytech**
## In this project, we successfully worked on the following:
- Embedding images
- Working with forms (buttons in this case)
- Floats and positioning
- The box model
- The <aside> tag was used for Editor's picks section on the rightmost side.
- Elements are aligned with a combination of all three techniques (float, flex, and grid).

### CODE REVIEW

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] The NY Times logo is a link (link to page)

- [ ] The Main title "Space Ripples Reveal Big Bang’s Smoking Gun" has to be more on the center as the original page.

- [ ] The first image on the page has to have a similar width to the original page.  

- [ ] The entire content text on the page has to have a similar width to the original page and has to have a smaller width than the main images.

- [ ] The second image on the page "The Theory of Inflation" has to have a similar width than the original page. 

- [ ] Video "Stanford Professor..." has to be center, the description of video title has to be center.

- [ ] Image has to have more width than the text here, consider follow the original page design. 





- [ ] On the "More in Space and Astronomy" Section, the images are overlapping with the text.



- [ ] Here is overlapping also with the 'The New York Times' section title. 



- [ ] 'The New York Times' section title (before the footer) has to be a link.

- [ ] Consider make more space between each other here, they are almost overlapping.



- [ ] Consider making the footer center as the original page.

- [ ] The footer should have a fixed position (it sticks to the bottom part of the screen).

[OPTIONAL]

- [ ] The 'Demo Link' on your readme file is not working, consider fix this.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by teekaytech** [comment]
## Thank you, SofiBretz for your feedback.

The above corrections have been made and changes have been effected. 
Kindly check out the updated project for the necessary action.

**Comment by uryelah** [comment]
Hello **Taofeek Olalere** & **Karthick Venkatesan**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**Great job fixing the changes from the last cr 🎇🎆**
There's still some work to be done so that your project is good to go, so hang in there.

---------    

**Great job at: 🥇** 
- positioning the main text of the page
- using semantic HTML
- using icons
- adding hover effects

**You still need to fix some minor issues below before you can move to the next project**

---------

### Required changes 🛠 

- [ ] The text under the video is floating up. Please fix it's positioning.
(Tip: [Read this](https://www.w3schools.com/Css/css_float.asp))
Screenshot_2020-03-06 NYT Clone


- [ ] Please fix the color of your links, it should be a similar shade of blue as the [original site](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html).
Screenshot_2020-03-06 NYT Clone(1)

---------

**Please fix the required changes 👷  before asking for a new code review**

---------

### Optional

- [ ] [Optional] You can also add `:hover`s to the buttons. And also `transition` to make it flashier.
Tip: [This article.](https://www.w3schools.com/howto/howto_css_transition_hover.asp)

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by karthi07** [comment]
Hi Sarah,
          We have fixed the required and optional changes. the Tips was really helpful :+1:  Please review and provide your comments.

**Comment by davidmrtz-dev** [comment]
### **Status: Approved.** ✅ 
### **Congragulations!** 🎉 
****
### Hi Team. 😄 
****
Great Job 💯  @karthi07 @teekaytech , You correctly implemented all the changes required by previous TSE.
You can move onto the next project. 🎊 
Happy coding! 😄 💻  
****
**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Pull request merged**
